# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='スキル名')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='タスク名')),
                ('image_path', models.ImageField(upload_to='')),
                ('description', models.TextField(verbose_name='詳細')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutoReal.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='チュートリアルの名前')),
                ('major', models.PositiveIntegerField()),
                ('minor', models.PositiveIntegerField()),
                ('image_path', models.ImageField(upload_to='', verbose_name='サムネイル')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tutorial',
            unique_together=set([('major', 'minor')]),
        ),
        migrations.AddField(
            model_name='skill',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutoReal.Tutorial'),
        ),
    ]
