# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutoReal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='チュートリアルの名前')),
                ('image_path', models.ImageField(upload_to='', verbose_name='サムネイル')),
            ],
        ),
    ]
