# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutoReal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='スキル名')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutoReal.Tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='タスク名')),
                ('image_path', models.ImageField(upload_to='')),
                ('description', models.TextField(verbose_name='詳細')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutoReal.Skill')),
            ],
        ),
    ]
