export const INCREMENT = 'INCREMENT';
export const SET_VIEW_STATE = 'SET_VIEW_STATE';
export const ADD_TUTOREAL = 'ADD_TUTOREAL';
export const SET_ACTIVE_TUTOREAL_INDEX = 'SET_ACTIVE_TUTOREAL_INDEX';
export const SET_ACTIVE_SKILL_INDEX = 'SET_ACTIVE_SKILL_INDEX';
export const SET_ACTIVE_TASK_INDEX = 'SET_ACTIVE_TASK_INDEX';
