export const INCREMENT = 'INCREMENT';
export const SET_TAB_INDEX = 'SET_TAB_INDEX';
export const SET_VIEW_STATE = 'SET_VIEW_STATE';
export const ADD_TUTOREAL = 'ADD_TUTOREAL';
export const SET_ACTIVE_TUTOREAL_INDEX = 'SET_ACTIVE_TUTOREAL_INDEX';
